using System.Diagnostics;

namespace DataverseGen.Core.Metadata;

public class GeneratorInfo
{
	public GeneratorInfo()
	{
		ProcessModule assembly = Process.GetCurrentProcess().MainModule;

		if (assembly is null)
		{
			throw new InvalidProgramException("Unable to get version from assembly.");
		}

		FileVersionInfo assemblyFileVersion = assembly.FileVersionInfo;

		WelcomeXml = $"""

					  // ------------------------------------------------------------------------------
					  // <auto-generated>
					  // This code was generated by a Dataverse-Cli.
					  // Runtime Version: {assemblyFileVersion.FileVersion}
					  // File Version: {assemblyFileVersion.FileVersion}
					  //
					  // Changes to this file may cause incorrect behavior and will be lost if
					  // the code is regenerated.
					  // </auto-generated>
					  // ------------------------------------------------------------------------------
					  """;

		GeneratedCodeAttribute =
			$"[System.CodeDom.Compiler.GeneratedCode(\"DataverseGen-Cli\",\"{assemblyFileVersion.FileVersion}\")]";
	}

	public string GeneratedCodeAttribute { get; }

	public string WelcomeXml { get; }
}