using System.Diagnostics;
using System.Reflection;

namespace DataverseGen.Core.Metadata
{
    public class GeneratorInfo
    {
        public GeneratorInfo()
        {
            Assembly assembly = Assembly.GetExecutingAssembly();
            string assemblyVersion = assembly.GetName().Version.ToString();
            FileVersionInfo assemblyFileVersion = FileVersionInfo.GetVersionInfo(assembly.Location);
            WelcomeXml = $@"
// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a Dataverse-Cli.
// Runtime Version: {assemblyVersion}
// File Version: {assemblyFileVersion.FileVersion}
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------";
            GeneratedCodeAttribute =
                $"[System.CodeDom.Compiler.GeneratedCode(\"DataverseGen-Cli\",\"{assemblyVersion}\")]";
        }

        public string GeneratedCodeAttribute { get; }
        public string WelcomeXml { get; }
    }
}