namespace DataverseGen.Core.Metadata
{
    public class GeneratorInfo
    {
        public GeneratorInfo()
        {
            System.Reflection.Assembly assembly = System.Reflection.Assembly.GetExecutingAssembly();
            string assemblyVersion = assembly.GetName().Version.ToString();
            System.Diagnostics.FileVersionInfo assemblyFileVersion = System.Diagnostics.FileVersionInfo.GetVersionInfo(assembly.Location);
            WelcomeXml = $@"
//------------------------------------------------------------------------------ 
    // <auto-generated> 
    // This code was generated by a Dataverse-Cli. 
    // Runtime Version: {assemblyVersion}
    // File Version: {assemblyFileVersion.FileVersion}
    // 
    // Changes to this file may cause incorrect behavior and will be lost if 
    // the code is regenerated. 
    // </auto-generated> 
    //------------------------------------------------------------------------------";
            GeneratedCodeAttribute =
                $"[System.CodeDom.Compiler.GeneratedCode(\"Dataverse-cli\",\"{assemblyVersion}\")]";
        }
        public string GeneratedCodeAttribute { get; }
        public string WelcomeXml { get; }
    }
}
