using DataverseGen.Core.Metadata;

namespace DataverseGen.Core.Tests.Metadata;

[TestClass]
public class GeneratorInfoTests
{
	[TestMethod]
	public void Constructor_SetsWelcomeXml_ContainsAutoGenerated()
	{
		var info = new GeneratorInfo();

		StringAssert.Contains(info.WelcomeXml, "auto-generated");
	}

	[TestMethod]
	public void Constructor_SetsWelcomeXml_ContainsDataverseCli()
	{
		var info = new GeneratorInfo();

		StringAssert.Contains(info.WelcomeXml, "Dataverse-Cli");
	}

	[TestMethod]
	public void Constructor_SetsWelcomeXml_ContainsRuntimeVersion()
	{
		var info = new GeneratorInfo();

		StringAssert.Contains(info.WelcomeXml, "Runtime Version:");
	}

	[TestMethod]
	public void Constructor_SetsGeneratedCodeAttribute_ContainsDataverseGenCli()
	{
		var info = new GeneratorInfo();

		StringAssert.Contains(info.GeneratedCodeAttribute, "DataverseGen-Cli");
	}

	[TestMethod]
	public void Constructor_SetsGeneratedCodeAttribute_HasAttributeSyntax()
	{
		var info = new GeneratorInfo();

		StringAssert.StartsWith(info.GeneratedCodeAttribute, "[System.CodeDom.Compiler.GeneratedCode(");
	}
}
